site_name: Self-Hosted Show Wiki
site_url: https://wiki.selfhosted.show
repo_url: https://github.com/selfhostedshow/wiki
theme:
  name: 'material'
  palette:
    primary: 'amber'
    accent: 'orange'
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/selfhostedshow'
    - type: 'twitter'
      link: 'https://twitter.com/selfhostedshow'
    - type: 'fire'
      link: 'https://fireside.com'
    - type: 'microphone'
      link: 'https://pocketcasts.com'
    - type: 'graduation-cap'
      link: 'https://linuxacademy.com'
    - type: 'linux'
      link: 'https://jupiterbroadcasting.com'
    - type: 'discord'
      link: 'https://discord.gg/n49fgkp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - mdx_include:
      base_path: docs
plugins:
  - search
  - minify:
      minify_html: true

strict: true
